import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationWrapper from "./components/navigationWrapper";
import { ToastProvider } from "@radix-ui/react-toast";
import { Toaster } from "./components/ui/toaster";
import { SidebarProvider,SidebarTrigger } from "./components/ui/sidebar";
import { AppSidebar } from "./components/sidebar/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
 className={`${geistSans.variable} ${geistMono.variable} antialiased`}
 suppressHydrationWarning
        >
        <ToastProvider>
          <SidebarProvider>
        {/* <NavigationWrapper/> */}
        <AppSidebar/>
        <SidebarTrigger/>
        {children}
        <Toaster />
        </SidebarProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
